// Central game registry. Add a game: drop a module in js/games/, add an entry here.
// `ink`   — the cabinet's spot colour; identifies the game on card, marquee and scores.
// `glyph` — original flat-ink art (inner markup of a 24x24 viewBox, fill: currentColor).
// `touch` — { pad, actions } describing the on-screen controls for coarse pointers.
//           pad: 'dpad' | 'lr' | 'ud' | null. actions: [{ a, label, aria }]
// `swipe` — true: a swipe on the screen is a d-pad press. An object remaps a
//           direction or adds a tap: { down: 'action', tap: 'up' }.
// `music` — a song id from audio.js SONGS, looped while playing.

export const GAMES = [
  {
    id: 'pong',
    name: 'Pong',
    ink: 'var(--flame)',
    category: 'Classique',
    difficulty: 2,
    description: "Deux raquettes, une balle, trois bips. L'angle de renvoi dépend de l'endroit touché.",
    glyph: '<rect x="2" y="7" width="2.4" height="10"/><rect x="19.6" y="9" width="2.4" height="10"/><circle cx="12" cy="12" r="2.4"/>',
    module: './games/pong.js',
    touch: { pad: 'ud', actions: [] },
    touchKeys: "Fais glisser ton doigt sur l’écran : la raquette le suit. Les flèches marchent aussi.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> ou la souris sur l’écran déplacent ta raquette.',
    higherIsBetter: true,
  },
  {
    id: 'pacman',
    name: 'Croque-Labyrinthe',
    ink: 'var(--amber)',
    category: 'Arcade',
    difficulty: 3,
    description: 'Quatre fantômes, quatre caractères. Les gélules inversent le rapport de force, les fruits paient.',
    glyph: '<path d="M21.6 6.2 12.4 12l9.2 5.8A10 10 0 1 1 21.6 6.2Z"/>',
    module: './games/pacman.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: "Glisse sur l’écran ou utilise la croix. Les tunnels latéraux traversent l’écran.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> pour te déplacer. Les tunnels latéraux traversent l\'écran.',
    higherIsBetter: true,
  },
  {
    id: 'tetris',
    name: 'Tetris',
    ink: 'var(--jade)',
    category: 'Puzzle',
    difficulty: 3,
    description: 'Sac de 7, pièce en garde, délai de verrouillage. Les règles modernes, au complet.',
    glyph: '<rect x="8" y="6" width="5" height="5"/><rect x="2" y="12" width="5" height="5"/><rect x="8" y="12" width="5" height="5"/><rect x="14" y="12" width="5" height="5"/>',
    module: './games/tetris.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Pose', aria: 'Poser la pièce' }, { a: 'hold', label: 'Garde', aria: 'Mettre la pièce en garde' }] },
    swipe: { down: 'action', tap: 'up' },
    music: 'korobeiniki',
    touchKeys: "Sur l’écran : glisse ← → pour déplacer, touche pour tourner, glisse ↓ pour poser. La croix et Garde restent dessous.",
    keys: '<kbd>←</kbd> <kbd>→</kbd> déplacent · <kbd>↑</kbd> tourne · <kbd>↓</kbd> accélère · <kbd>Espace</kbd> pose d\'un coup · <kbd>C</kbd> met en garde.',
    higherIsBetter: true,
  },
  {
    id: 'invaders',
    name: 'Vague Zéro',
    ink: 'var(--grape)',
    category: 'Action',
    difficulty: 3,
    description: 'Onze colonnes qui marchent au rythme du cœur. Un seul tir à la fois, et une soucoupe à abattre.',
    glyph: '<path d="M6 6h2v2H6zM16 6h2v2h-2zM8 8h8v2H8zM6 10h12v2H6zM4 12h16v2H4zM4 14h4v2H4zM16 14h4v2h-4zM8 16h2v2H8zM14 16h2v2h-2z"/>',
    module: './games/invaders.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Tir', aria: 'Tirer' }] },
    touchKeys: "← → déplacent le canon, Tir tire.",
    keys: '<kbd>←</kbd> <kbd>→</kbd> déplacent le canon · <kbd>Espace</kbd> tire.',
    higherIsBetter: true,
  },
  {
    id: 'snake',
    name: 'Serpent',
    ink: 'var(--lime)',
    category: 'Arcade',
    difficulty: 2,
    description: 'Il grandit, tu rétrécis. Les virages sont mis en file : tes doubles appuis passent.',
    glyph: '<path d="M4 4h10v4H8v4h10v8H6v-4h8v-2H4z"/>',
    module: './games/snake.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: "Glisse sur l’écran ou utilise la croix pour tourner. Le carré doré rapporte gros, mais il expire.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> pour tourner. Le carré doré rapporte gros, mais il expire.',
    higherIsBetter: true,
  },
  {
    id: 'breakout',
    name: 'Casse-Brique',
    ink: 'var(--azure)',
    category: 'Arcade',
    difficulty: 2,
    description: "Huit rangées, quatre couleurs. La balle accélère, la raquette rétrécit au plafond — les règles de 1976.",
    glyph: '<rect x="2" y="4" width="6" height="3"/><rect x="9" y="4" width="6" height="3"/><rect x="16" y="4" width="6" height="3"/><rect x="5" y="9" width="6" height="3"/><rect x="12" y="9" width="6" height="3"/><rect x="7" y="19" width="10" height="3"/><circle cx="12" cy="15" r="2"/>',
    module: './games/breakout.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Lancer', aria: 'Lancer la balle' }] },
    touchKeys: "Fais glisser ton doigt sur l’écran : la raquette le suit. Touche pour lancer.",
    keys: 'La souris ou <kbd>←</kbd> <kbd>→</kbd> déplacent la raquette · <kbd>Espace</kbd> lance la balle.',
    higherIsBetter: true,
  },
  {
    id: '2048',
    name: '2048',
    ink: 'var(--rose)',
    category: 'Puzzle',
    difficulty: 2,
    description: 'Pousse la grille, fusionne les paires. Atteindre 2048 est une victoire, pas une fin.',
    glyph: '<rect x="2" y="2" width="9" height="9"/><rect x="13" y="2" width="9" height="9"/><rect x="2" y="13" width="9" height="9"/><rect x="13" y="13" width="9" height="9" opacity=".45"/>',
    module: './games/2048.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: "Glisse sur la grille (ou utilise la croix) pour tout pousser.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> poussent toute la grille.',
    higherIsBetter: true,
  },
  {
    id: 'minesweeper',
    name: 'Démineur',
    ink: 'var(--steel)',
    category: 'Puzzle',
    difficulty: 4,
    description: 'Trente mines, aucune devinette au premier clic : la grille se pose autour de toi.',
    glyph: '<circle cx="12" cy="13" r="6"/><rect x="11" y="3" width="2" height="5"/><rect x="3" y="12" width="4" height="2"/><rect x="17" y="12" width="4" height="2"/>',
    module: './games/minesweeper.js',
    touch: { pad: null, actions: [{ a: 'action', label: 'Drapeau', aria: 'Basculer le mode drapeau' }] },
    livesLabel: 'Mines',   // this game reports mines left, not lives
    touchKeys: "Touche une case pour la révéler. Drapeau bascule le mode : la case suivante reçoit un drapeau.",
    keys: 'Clic pour révéler · clic droit pour poser un drapeau · <kbd>F</kbd> bascule le mode drapeau.',
    higherIsBetter: true,
  },
  {
    id: 'simon',
    name: 'Simon',
    ink: 'var(--rose)',
    category: 'Réflexe',
    difficulty: 2,
    description: "Regarde la séquence, refais-la. Chaque quartier a sa note : ça s'écoute autant que ça se voit.",
    glyph: '<path d="M12 2a10 10 0 0 1 10 10h-7a3 3 0 0 0-3-3z"/><path d="M22 12a10 10 0 0 1-10 10v-7a3 3 0 0 0 3-3z" opacity=".75"/><path d="M12 22A10 10 0 0 1 2 12h7a3 3 0 0 0 3 3z" opacity=".55"/><path d="M2 12A10 10 0 0 1 12 2v7a3 3 0 0 0-3 3z" opacity=".35"/>',
    module: './games/simon.js',
    touch: { pad: 'dpad', actions: [] },
    livesLabel: 'Erreurs',
    touchKeys: "Touche directement les quartiers de couleur à l’écran.",
    keys: 'Clique un quartier, ou <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> <kbd>←</kbd> pour les quatre couleurs.',
    higherIsBetter: true,
  },
  {
    id: 'flappy',
    name: "Bat d'Aile",
    ink: 'var(--jade)',
    category: 'Réflexe',
    difficulty: 4,
    description: 'Une seule touche. Les ouvertures se resserrent à mesure que tu passes.',
    glyph: '<path d="M4 6h5v3H4zM14 2h6v20h-6zM4 15h5v3H4z"/><circle cx="11" cy="12" r="2.6"/>',
    module: './games/flappy.js',
    touch: { pad: null, actions: [{ a: 'action', label: 'Voler', aria: 'Battre des ailes' }] },
    touchKeys: "Voler — ou une touche n’importe où sur l’écran — bat des ailes.",
    keys: '<kbd>Espace</kbd> (ou un clic) pour battre des ailes.',
    higherIsBetter: true,
  },
  {
    id: 'connect4',
    name: 'Puissance 4',
    ink: 'var(--azure)',
    category: 'Réflexion',
    difficulty: 3,
    description: "Contre une IA qui anticipe. Enchaîne les manches : ton score, c'est ta série.",
    glyph: '<rect x="2" y="4" width="20" height="18" rx="2" opacity=".35"/><circle cx="7" cy="17" r="2.4"/><circle cx="12" cy="17" r="2.4"/><circle cx="12" cy="12" r="2.4"/><circle cx="17" cy="17" r="2.4"/>',
    module: './games/connect4.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Poser', aria: 'Poser un jeton' }] },
    livesLabel: 'Série',
    touchKeys: "Touche une colonne à l’écran pour y poser ton jeton.",
    keys: 'Clique une colonne, ou <kbd>←</kbd> <kbd>→</kbd> pour viser et <kbd>Espace</kbd> pour poser.',
    higherIsBetter: true,
  },
  {
    id: 'memory',
    name: 'Paires',
    ink: 'var(--lime)',
    category: 'Réflexion',
    difficulty: 2,
    description: 'Retourne deux cartes, garde la paire. Moins de coups et moins de temps : plus de points.',
    glyph: '<rect x="2" y="3" width="8" height="8" rx="1"/><rect x="14" y="3" width="8" height="8" rx="1" opacity=".4"/><rect x="2" y="13" width="8" height="8" rx="1" opacity=".4"/><rect x="14" y="13" width="8" height="8" rx="1"/>',
    module: './games/memory.js',
    touch: { pad: null, actions: [] },
    livesLabel: 'Coups',
    touchKeys: "Touche une carte à l’écran pour la retourner.",
    keys: 'Clique (ou touche) une carte pour la retourner.',
    higherIsBetter: true,
  },
  {
    id: 'asteroids',
    name: 'Astéroïdes',
    ink: 'var(--steel)',
    category: 'Action',
    difficulty: 4,
    description: 'Un vaisseau, de l’inertie et des rochers qui se brisent en trois tailles. En traits lumineux, comme en 1979.',
    glyph: '<path d="M3 13.5 6.5 10h4l2.5 2.5-1.2 3 2 2.3-2.3 3.2H7l-4-2.6z" opacity=".55"/><path d="M17.5 2 22 12l-4.5-2.4L13 12z"/>',
    module: './games/asteroids.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Tir', aria: 'Tirer' }] },
    touchKeys: "← → tournent, ↑ pousse, ↓ hyperespace (risqué) · Tir tire.",
    keys: '<kbd>←</kbd> <kbd>→</kbd> tournent · <kbd>↑</kbd> pousse · <kbd>Espace</kbd> tire · <kbd>↓</kbd> hyperespace.',
    higherIsBetter: true,
  },
  {
    id: 'frogger',
    name: 'Traversée',
    ink: 'var(--lime)',
    category: 'Arcade',
    difficulty: 3,
    description: 'Cinq voies de circulation, une rivière, cinq abris à rejoindre. Les tortues plongent sans prévenir.',
    glyph: '<path d="M7 3h3v3H7zM14 3h3v3h-3zM6 6h12v9H6zM3 8h3v4H3zM18 8h3v4h-3zM3 15h5v5H3zM16 15h5v5h-5zM9 15h6v3H9z"/>',
    module: './games/frogger.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: "Glisse sur l’écran ou touche la croix : un saut par geste.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> : un saut par appui.',
    higherIsBetter: true,
  },
  {
    id: 'missile',
    name: 'Riposte',
    ink: 'var(--flame)',
    category: 'Action',
    difficulty: 3,
    description: 'Six villes, trois silos, des missiles qui tombent. Vise devant eux : les explosions s’enchaînent.',
    glyph: '<circle cx="15" cy="9" r="5"/><path d="M2 20h20v2H2zM4 17h3v3H4zM10.5 16h3v4h-3zM17 17h3v3h-3zM2.6 2 4 1.2 10 11.5l-1.4.8z"/>',
    module: './games/missile.js',
    touch: { pad: null, actions: [] },
    livesLabel: 'Villes',
    touchKeys: "Touche l’écran là où le missile va passer : le silo le plus proche tire.",
    keys: 'Clique où le missile va passer, ou vise avec <kbd>←</kbd> <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> et tire avec <kbd>Espace</kbd>.',
    higherIsBetter: true,
  },
  {
    id: 'galaxian',
    name: 'Galaxie',
    ink: 'var(--grape)',
    category: 'Action',
    difficulty: 3,
    description: 'Une flotte qui ondule, des pillards qui plongent en piqué, des vaisseaux amiraux escortés. Un tir à la fois.',
    glyph: '<path d="M7 3h2v2H7zM15 3h2v2h-2zM6 5h12v3H6zM4 8h16v3H4zM4 11h3v3H4zM17 11h3v3h-3z"/><path d="M11 15h2v3h2v3H9v-3h2z" opacity=".55"/>',
    module: './games/galaxian.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Tir', aria: 'Tirer' }] },
    touchKeys: '← → déplacent le vaisseau, Tir tire. Un amiral abattu en piqué après ses escortes vaut 800.',
    keys: '<kbd>←</kbd> <kbd>→</kbd> déplacent le vaisseau · <kbd>Espace</kbd> tire.',
    higherIsBetter: true,
  },
  {
    id: 'centipede',
    name: 'Mille-pattes',
    ink: 'var(--lime)',
    category: 'Action',
    difficulty: 3,
    description: 'Il descend entre les champignons et se coupe en deux à chaque tir. L’araignée rôde dans ton coin.',
    glyph: '<circle cx="5" cy="12" r="3"/><circle cx="11" cy="12" r="3" opacity=".75"/><circle cx="17" cy="12" r="3" opacity=".55"/><path d="M3 4h5v3H3zM16 3h5v3h-5zM10 18h4v4h-4z" opacity=".4"/>',
    module: './games/centipede.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Tir', aria: 'Tirer' }] },
    touchKeys: 'La croix déplace ton canon dans la zone du bas, Tir tire (garde appuyé pour tirer en continu).',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> déplacent le canon · <kbd>Espace</kbd> tire (maintenu : en continu).',
    higherIsBetter: true,
  },
  {
    id: 'lander',
    name: 'Alunissage',
    ink: 'var(--steel)',
    category: 'Réflexion',
    difficulty: 4,
    description: 'Dose la poussée, redresse le module, pose-toi en douceur. Plus la piste est étroite, plus elle paie.',
    glyph: '<path d="M8 3h8l2 4v3H6V7zM5 10h14v3H5zM6 13l-3 6h2l3-6zM18 13l3 6h-2l-3-6z"/><path d="M1 21h22v1.5H1z" opacity=".5"/>',
    module: './games/lander.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Poussée', aria: 'Allumer le moteur' }] },
    livesLabel: 'Carburant',
    touchKeys: '← → inclinent le module, ↑ ou Poussée allume le moteur. Vitesses en rouge : trop vite pour se poser.',
    keys: '<kbd>←</kbd> <kbd>→</kbd> inclinent · <kbd>↑</kbd> ou <kbd>Espace</kbd> pour la poussée.',
    higherIsBetter: true,
  },
  {
    id: 'lightcycles',
    name: 'Motos lumière',
    ink: 'var(--azure)',
    category: 'Réflexe',
    difficulty: 3,
    description: 'Chaque moto laisse un mur de lumière. Coince les autres, ne touche rien. Un rival de plus à chaque manche.',
    glyph: '<path d="M2 4h10v3H5v10H2zM12 4h3v12h7v3H12z" opacity=".55"/><path d="M4 16h3v3H4zM19 7h3v3h-3z"/>',
    module: './games/lightcycles.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: 'Glisse sur l’écran ou touche la croix pour tourner. Deux appuis rapides comptent tous les deux.',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> pour tourner.',
    higherIsBetter: true,
  },
  {
    id: 'doom',
    name: 'Freedoom',
    ink: 'var(--flame)',
    category: 'Action',
    difficulty: 4,
    description: 'Le moteur de Doom (1993) avec Freedoom, un Doom complet et libre en 4 épisodes. Tu as le jeu original ? Charge ton DOOM.WAD.',
    glyph: '<path d="M4 3h16l-1.5 4H17v3l2 2-2 1v6l-5 3-5-3v-6l-2-1 2-2V7H5.5z" opacity=".35"/><path d="M8.5 11h2.5v2.5H8.5zM13 11h2.5v2.5H13zM10 16.5h4V18h-4z"/>',
    module: './games/doom.js',
    custom: true,            // its own menus, skills and saves: no score, level or difficulty strip
    ownsEsc: true,           // Esc opens the engine's menu, so the page doesn't add "Échap met en pause"
    note: 'Premier lancement : environ 29 Mo à télécharger, puis gardés en cache pour jouer hors ligne.',
    filePicker: { accept: '.wad,.WAD', label: 'Charger mon DOOM.WAD' },
    touch: { pad: 'dpad', actions: [
      { a: 'action', label: 'Tir', aria: 'Tirer, ou valider dans les menus' },
      { a: 'hold', label: 'Ouvrir', aria: 'Ouvrir une porte, actionner un levier' },
      { a: 'weapon', label: 'Arme', aria: 'Arme suivante' },
      { a: 'menu', label: 'Menu', aria: 'Ouvrir le menu' },
    ] },
    touchKeys: 'Croix : avancer et tourner · Tir (valide aussi les menus) · Ouvrir les portes · Arme suivante · Menu. Tu cours en permanence. Sauvegardes gardées dans ce navigateur.',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> · <kbd>Ctrl</kbd> tire · <kbd>Espace</kbd> ouvre · <kbd>Maj</kbd> court · <kbd>Alt</kbd>+flèches ou <kbd>,</kbd> <kbd>.</kbd> en pas de côté · <kbd>1</kbd>–<kbd>7</kbd> armes · <kbd>Tab</kbd> carte · <kbd>Échap</kbd> menu (sauvegarder, charger, difficulté) · <kbd>Maj</kbd>+<kbd>Tab</kbd> rend le clavier à la page.',
    higherIsBetter: true,
  },
  {
    id: 'lights',
    name: 'Éteins-Tout',
    ink: 'var(--amber)',
    category: 'Puzzle',
    difficulty: 2,
    description: 'Chaque case inverse ses voisines. Plonge tout le plateau dans le noir, avec le moins de coups possible.',
    glyph: '<rect x="9" y="3" width="6" height="6" rx="1.4"/><rect x="3" y="9" width="6" height="6" rx="1.4"/><rect x="9" y="9" width="6" height="6" rx="1.4"/><rect x="15" y="9" width="6" height="6" rx="1.4"/><rect x="9" y="15" width="6" height="6" rx="1.4"/><rect x="3" y="3" width="6" height="6" rx="1.4" opacity=".3"/><rect x="15" y="3" width="6" height="6" rx="1.4" opacity=".3"/><rect x="3" y="15" width="6" height="6" rx="1.4" opacity=".3"/><rect x="15" y="15" width="6" height="6" rx="1.4" opacity=".3"/>',
    module: './games/lights.js',
    touch: { pad: null, actions: [{ a: 'hold', label: 'Indice', aria: 'Montrer une case à jouer (moins 150 points)' }] },
    touchKeys: 'Touche une case pour l’inverser avec ses voisines. « Indice » montre une case à jouer (−150 points).',
    livesLabel: 'Coups',
    keys: 'Clic, ou <kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> puis <kbd>Espace</kbd> pour appuyer · <kbd>C</kbd> donne un indice (−150 points).',
    higherIsBetter: true,
  },
  {
    id: 'slide',
    name: 'Taquin',
    ink: 'var(--azure)',
    category: 'Puzzle',
    difficulty: 3,
    description: 'Fais coulisser les tuiles pour les remettre en ordre. Le mélange est toujours résoluble : les couleurs t’aident autant que les chiffres.',
    glyph: '<rect x="2.5" y="2.5" width="5.6" height="5.6" rx="1.2"/><rect x="9" y="2.5" width="5.6" height="5.6" rx="1.2"/><rect x="15.5" y="2.5" width="5.6" height="5.6" rx="1.2"/><rect x="2.5" y="9" width="5.6" height="5.6" rx="1.2"/><rect x="9" y="9" width="5.6" height="5.6" rx="1.2"/><rect x="15.5" y="9" width="5.6" height="5.6" rx="1.2"/><rect x="2.5" y="15.5" width="5.6" height="5.6" rx="1.2"/><rect x="9" y="15.5" width="5.6" height="5.6" rx="1.2"/>',
    module: './games/slide.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: 'Touche une tuile, ou glisse sur le plateau : elle coulisse vers la case vide.',
    livesLabel: 'Coups',
    keys: 'Clic sur une tuile, ou <kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> : la tuile se déplace dans le sens de la flèche.',
    higherIsBetter: true,
  },
  {
    id: 'hanoi',
    name: 'Tour de Hanoï',
    ink: 'var(--jade)',
    category: 'Réflexion',
    difficulty: 2,
    description: 'Déplace la pile de disques sur le piquet de droite, un seul à la fois, sans jamais poser un grand disque sur un petit.',
    glyph: '<rect x="2" y="19.5" width="20" height="2" rx="1"/><rect x="4.6" y="6" width="1.6" height="13.5" opacity=".4"/><rect x="11.2" y="6" width="1.6" height="13.5" opacity=".4"/><rect x="17.8" y="6" width="1.6" height="13.5" opacity=".4"/><rect x="2" y="16" width="8.4" height="3" rx="1.5"/><rect x="3" y="12.8" width="6.4" height="3" rx="1.5"/><rect x="4" y="9.6" width="4.4" height="3" rx="1.5"/>',
    module: './games/hanoi.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Disque', aria: 'Prendre ou poser le disque' }] },
    touchKeys: 'Touche un piquet pour en prendre le disque du dessus, puis un autre piquet pour le poser.',
    livesLabel: 'Coups',
    keys: 'Clic sur un piquet pour prendre ou poser · ou <kbd>←</kbd> <kbd>→</kbd> pour choisir, <kbd>Espace</kbd> pour prendre/poser (<kbd>↑</kbd> prend, <kbd>↓</kbd> pose).',
    higherIsBetter: true,
  },
  {
    id: 'whack',
    name: 'Tape-Taupe',
    ink: 'var(--lime)',
    category: 'Réflexe',
    difficulty: 2,
    description: 'Neuf trous, un chronomètre. Tape les taupes, évite les bombes : les séries multiplient tes points, la taupe dorée en vaut cinq.',
    glyph: '<ellipse cx="12" cy="19.5" rx="9.5" ry="2.5" opacity=".4"/><path d="M5 19.5a7 7 0 0 1 14 0z"/><circle cx="12" cy="15.8" r="1.5" opacity=".4"/><rect x="3" y="3" width="5" height="5" rx="1.2" opacity=".3"/><rect x="16" y="3" width="5" height="5" rx="1.2" opacity=".3"/>',
    module: './games/whack.js',
    touch: { pad: null, actions: [] },
    touchKeys: 'Touche les taupes — jamais les bombes noires. La taupe dorée vaut 50.',
    livesLabel: 'Temps',
    keys: 'Clic sur les taupes, ou touches <kbd>1</kbd>–<kbd>9</kbd> comme un pavé numérique (<kbd>7</kbd> <kbd>8</kbd> <kbd>9</kbd> en haut). Pas les bombes !',
    higherIsBetter: true,
  },
  {
    id: 'jump',
    name: 'Saute-Nuages',
    ink: 'var(--grape)',
    category: 'Arcade',
    difficulty: 3,
    description: 'Il rebondit tout seul : toi, tu diriges. Grimpe de nuage en nuage, profite des ressorts, méfie-toi des nuages d’orage qui s’effritent.',
    glyph: '<path d="M5 19h14a3 3 0 0 0 0-6 4 4 0 0 0-7.4-1.6A3.5 3.5 0 0 0 5 13a3 3 0 0 0 0 6z" opacity=".45"/><circle cx="12" cy="6.5" r="3.4"/>',
    module: './games/jump.js',
    touch: { pad: 'lr', actions: [] },
    touchKeys: 'Fais glisser ton doigt sur l’écran : le personnage rebondit tout seul et te suit. Les flèches marchent aussi.',
    keys: '<kbd>←</kbd> <kbd>→</kbd> (ou la souris sur l’écran) pour diriger : il rebondit tout seul. L’écran se referme sur les côtés.',
    higherIsBetter: true,
  },
  {
    id: 'runner',
    name: 'Cosmo-Course',
    ink: 'var(--flame)',
    category: 'Réflexe',
    difficulty: 3,
    description: 'Un cosmonaute court sur une planète néon. Saute les rochers — mais surtout pas sous un drone — et ramasse les étoiles.',
    glyph: '<circle cx="14.5" cy="4.8" r="2.6"/><path d="M4.5 19.5 9 13.2l3.6 1.6 2.6-5.6 4.3 2" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"/><rect x="2.5" y="20.8" width="19" height="1.8" rx=".9" opacity=".5"/>',
    music: 'course',
    module: './games/runner.js',
    touch: { pad: null, actions: [{ a: 'action', label: 'Saut', aria: 'Sauter (plus longtemps appuyé : plus haut)' }] },
    touchKeys: 'Touche l’écran ou « Saut » : reste appuyé pour sauter plus haut. Ne saute pas sous un drone !',
    keys: '<kbd>Espace</kbd> ou <kbd>↑</kbd> (ou un clic) pour sauter — plus longtemps appuyé, plus haut. Saute les rochers, pas sous les drones.',
    higherIsBetter: true,
  },
  {
    id: 'hockey',
    name: 'Hockey de Table',
    ink: 'var(--azure)',
    category: 'Action',
    difficulty: 3,
    description: 'Le palet glisse presque sans frottement et rebondit sur les bords. Place ton maillet et marque avant la machine.',
    glyph: '<circle cx="9" cy="14.5" r="5.5" opacity=".45"/><circle cx="9" cy="14.5" r="2.4"/><circle cx="17.5" cy="7" r="2.7"/><rect x="2" y="2.5" width="20" height="1.6" rx=".8" opacity=".5"/>',
    module: './games/hockey.js',
    touch: { pad: null, actions: [] },
    touchKeys: 'Fais glisser ton doigt sur ta moitié de table : le maillet te suit.',
    keys: 'La souris (ou <kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd>) déplace ton maillet, dans la moitié basse. Le premier au score cible gagne.',
    higherIsBetter: true,
  },
  {
    id: 'reversi',
    name: 'Reversi',
    ink: 'var(--jade)',
    category: 'Réflexion',
    difficulty: 3,
    description: 'Encadre une ligne de pions adverses entre deux des tiens : ils changent tous de couleur. L’IA aime les coins et les bords.',
    glyph: '<circle cx="8.5" cy="12" r="5.6"/><circle cx="15.5" cy="12" r="5.6" opacity=".4"/>',
    module: './games/reversi.js',
    touch: { pad: null, actions: [{ a: 'hold', label: 'Indice', aria: 'Suggérer un coup' }] },
    touchKeys: 'Touche une case pour poser un pion : les points clairs montrent les coups possibles. « Indice » suggère un coup.',
    livesLabel: 'Pions',
    keys: 'Clic sur une case, ou <kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> puis <kbd>Espace</kbd> · <kbd>C</kbd> donne un indice.',
    higherIsBetter: true,
  },
  {
    id: 'gems',
    name: 'Gemmes',
    ink: 'var(--rose)',
    category: 'Puzzle',
    difficulty: 2,
    description: 'Échange deux gemmes voisines pour en aligner trois ou plus. Quatre font une gemme rayée, cinq une arc-en-ciel : enchaîne les combos avant la fin des coups.',
    glyph: '<path d="M12 2.5 18.5 9 12 21.5 5.5 9z"/><path d="M5.5 9h13M9.2 9 12 2.5 14.8 9 12 21.5z" fill="none" stroke="#000" stroke-opacity=".28" stroke-width="1.1"/>',
    module: './games/gems.js',
    touch: { pad: null, actions: [{ a: 'hold', label: 'Indice', aria: 'Montrer un échange possible' }] },
    touchKeys: 'Glisse une gemme vers sa voisine, ou touche l’une puis l’autre. « Indice » montre un échange possible.',
    livesLabel: 'Coups',
    keys: 'Glisse une gemme vers sa voisine, ou clic sur l’une puis l’autre · clavier : <kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> déplacent le curseur, <kbd>Espace</kbd> prend une gemme et une flèche l’échange · <kbd>C</kbd> donne un indice.',
    higherIsBetter: true,
  },
  {
    id: 'bubbles',
    name: 'Bulles',
    ink: 'var(--lime)',
    category: 'Arcade',
    difficulty: 3,
    description: 'Un nid de bulles pend au plafond. Vise, tire, relie trois couleurs identiques : les grappes sans appui tombent. Trop de tirs ratés et le plafond descend.',
    glyph: '<circle cx="8" cy="8" r="4.6"/><circle cx="17" cy="9.5" r="4.2" opacity=".55"/><circle cx="12" cy="17.5" r="4.6" opacity=".8"/>',
    module: './games/bubbles.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Tir', aria: 'Tirer' }, { a: 'hold', label: 'Échange', aria: 'Échanger avec la bulle suivante' }] },
    touchKeys: 'Fais glisser le doigt pour viser, relâche pour tirer. « Échange » permute avec la bulle suivante.',
    livesLabel: 'Avant chute',
    keys: 'La souris vise, un clic tire — ou <kbd>←</kbd> <kbd>→</kbd> pour tourner et <kbd>Espace</kbd> pour tirer · <kbd>C</kbd> échange avec la bulle suivante.',
    higherIsBetter: true,
  },
  {
    id: 'sokoban',
    name: 'Entrepôt',
    ink: 'var(--amber)',
    category: 'Puzzle',
    difficulty: 3,
    description: 'Pousse chaque caisse sur une marque. Une caisse ne bouge que si rien ne la bloque — et un coin, c’est définitif.',
    glyph: '<rect x="12" y="12" width="9" height="9" rx="1.5"/><path d="M6.5 3 10 6.5 6.5 10 3 6.5z"/><path d="M4 14.5h5v2H4zM14.5 4h2v5h-2z" opacity=".4"/>',
    module: './games/sokoban.js',
    touch: { pad: 'dpad', actions: [{ a: 'hold', label: 'Annuler', aria: 'Annuler le dernier coup' }] },
    swipe: true,
    livesLabel: 'Coups',
    touchKeys: 'Touche une case autour de toi pour avancer d’un pas, ou utilise la croix. « Annuler » revient d’un coup en arrière.',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> pour pousser · <kbd>C</kbd> ou <kbd>Espace</kbd> annule le dernier coup.',
    higherIsBetter: true,
  },
  {
    id: 'motus',
    name: 'Le Mot',
    ink: 'var(--grape)',
    category: 'Réflexion',
    difficulty: 3,
    description: 'Trois mots de cinq lettres à trouver. Vert : bonne lettre bien placée. Orange : elle est dans le mot, ailleurs. La première lettre est donnée.',
    glyph: '<rect x="1.5" y="6" width="4" height="4.5" rx="1"/><rect x="6.5" y="6" width="4" height="4.5" rx="1" opacity=".35"/><rect x="11.5" y="6" width="4" height="4.5" rx="1"/><rect x="16.5" y="6" width="4" height="4.5" rx="1" opacity=".35"/><rect x="1.5" y="13.5" width="4" height="4.5" rx="1" opacity=".35"/><rect x="6.5" y="13.5" width="4" height="4.5" rx="1"/><rect x="11.5" y="13.5" width="4" height="4.5" rx="1" opacity=".35"/><rect x="16.5" y="13.5" width="4" height="4.5" rx="1" opacity=".35"/>',
    module: './games/motus.js',
    touch: { pad: null, actions: [{ a: 'action', label: 'Valider', aria: 'Valider le mot' }, { a: 'hold', label: 'Effacer', aria: 'Effacer la dernière lettre' }] },
    livesLabel: 'Essais',
    touchKeys: 'Le clavier est à l’écran : touche les lettres, ⌫ efface, ⏎ valide.',
    keys: 'Tape le mot au clavier · <kbd>Entrée</kbd> valide · <kbd>Retour arrière</kbd> efface. Mots sans accent.',
    higherIsBetter: true,
  },
  {
    id: 'defense',
    name: 'Défense',
    ink: 'var(--jade)',
    category: 'Réflexion',
    difficulty: 4,
    description: 'Les créatures suivent toujours la même route ; à toi de la border. Canon pour les dégâts, Givre pour les ralentir, trois niveaux par tour.',
    glyph: '<path d="M8 21h8l-1-9H9z"/><path d="M7.5 9h9v3h-9z"/><path d="M9 9V5l3-2 3 2v4" opacity=".5"/><circle cx="4" cy="5" r="1.7" opacity=".55"/><circle cx="20" cy="5" r="1.7" opacity=".55"/>',
    module: './games/defense.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Bâtir', aria: 'Bâtir ou améliorer la tour' }, { a: 'hold', label: 'Tour', aria: 'Changer de type de tour' }] },
    livesLabel: 'Vies',
    touchKeys: 'Touche un emplacement pour bâtir, une tour pour l’améliorer. Le bandeau du haut change de type de tour.',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> choisissent l’emplacement · <kbd>Espace</kbd> bâtit ou améliore · <kbd>C</kbd> change de tour.',
    higherIsBetter: true,
  },
  {
    id: 'caverne',
    name: 'Caverne',
    ink: 'var(--azure)',
    category: 'Arcade',
    difficulty: 3,
    description: 'Cinq salles, des pics, de la lave et des gemmes. Plus tu gardes la touche de saut, plus tu montes. La porte est toujours atteignable ; les gemmes, non.',
    glyph: '<rect x="2" y="17" width="9" height="2.5" rx="1.2"/><rect x="13.5" y="12" width="8.5" height="2.5" rx="1.2" opacity=".55"/><circle cx="6.5" cy="11.6" r="2.5"/><rect x="5" y="14" width="3" height="3"/><path d="M17.8 5 20.4 7.6 17.8 10.2 15.2 7.6z" opacity=".8"/>',
    music: 'caverne',
    module: './games/caverne.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Saut', aria: 'Sauter (plus longtemps appuyé : plus haut)' }] },
    touchKeys: 'Touche la gauche ou la droite de l’écran pour marcher, la droite de l’écran ou « Saut » pour sauter. La croix reste dessous.',
    keys: '<kbd>←</kbd> <kbd>→</kbd> pour courir · <kbd>Espace</kbd> ou <kbd>↑</kbd> pour sauter (maintenu : plus haut).',
    higherIsBetter: true,
  },
  {
    id: 'flipper',
    name: 'Flipper',
    ink: 'var(--grape)',
    category: 'Action',
    difficulty: 3,
    new: true,
    description: 'Une vraie petite table : bumpers qui paient, cibles tombantes qui montent le multiplicateur, et un couloir central qui ne pardonne pas.',
    glyph: '<circle cx="8" cy="7" r="2.6"/><circle cx="16" cy="7" r="2.6"/><circle cx="12" cy="12" r="3"/><path d="M4 16.5 10 20v2l-6-3.5z"/><path d="M20 16.5 14 20v2l6-3.5z"/>',
    module: './games/flipper.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Lance', aria: 'Lancer la bille' }] },
    touchKeys: 'Touche la moitié gauche ou droite de l’écran pour le flip correspondant. « Lance » envoie la bille.',
    keys: '<kbd>←</kbd> <kbd>→</kbd> actionnent les flips · <kbd>Espace</kbd> lance la bille. Les cinq cibles du haut montent le multiplicateur.',
    livesLabel: 'Billes',
    higherIsBetter: true,
  },
  {
    id: 'rally',
    name: 'Rallye',
    ink: 'var(--lime)',
    category: 'Réflexe',
    difficulty: 3,
    new: true,
    description: 'Quatre voies, du trafic qui se densifie et un réservoir qui descend. Les bidons verts refont le plein ; doubler rapporte.',
    glyph: '<rect x="8" y="2" width="8" height="12" rx="2"/><rect x="9.5" y="16" width="5" height="6" rx="1.5" opacity=".55"/><rect x="2" y="7" width="2.5" height="10" rx="1.2" opacity=".4"/><rect x="19.5" y="7" width="2.5" height="10" rx="1.2" opacity=".4"/>',
    music: 'course',
    module: './games/rally.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Gaz', aria: 'Accélérer' }] },
    touchKeys: 'Fais glisser ton doigt : la voiture suit. « Gaz » accélère (et fait monter le score plus vite).',
    keys: '<kbd>←</kbd> <kbd>→</kbd> braquent · <kbd>↑</kbd> accélère · <kbd>↓</kbd> freine. La souris braque aussi.',
    livesLabel: 'Voitures',
    higherIsBetter: true,
  },
  {
    id: 'plateformes',
    name: 'Plateformes',
    ink: 'var(--amber)',
    category: 'Arcade',
    difficulty: 3,
    new: true,
    description: 'Six tableaux d’un écran : pièces, piques, marcheurs à écraser et un drapeau au bout. Lâcher la touche de saut coupe le saut — tout est dans le dosage.',
    glyph: '<rect x="2" y="12" width="7" height="2.5" rx="1"/><rect x="13" y="8" width="9" height="2.5" rx="1" opacity=".6"/><rect x="2" y="20" width="20" height="3" rx="1" opacity=".4"/><rect x="4.5" y="7" width="4" height="5" rx="1"/><circle cx="17" cy="4.5" r="2"/>',
    music: 'caverne',
    module: './games/plateformes.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Saut', aria: 'Sauter' }] },
    touchKeys: '← → pour courir, « Saut » pour sauter — maintenu, tu montes plus haut. Saute sur les marcheurs pour les écraser.',
    keys: '<kbd>←</kbd> <kbd>→</kbd> pour courir · <kbd>Espace</kbd> ou <kbd>↑</kbd> pour sauter (maintenu : plus haut). Retomber sur un marcheur l’écrase.',
    livesLabel: 'Vies',
    higherIsBetter: true,
  },
  {
    id: 'bombes',
    name: 'Bombes',
    ink: 'var(--rose)',
    category: 'Action',
    difficulty: 3,
    new: true,
    description: 'Un labyrinthe de piliers, des briques qui sautent et une sortie cachée dessous. Ta bombe ne fait pas la différence entre toi et les autres.',
    glyph: '<circle cx="12" cy="14" r="7"/><rect x="11" y="4" width="2" height="4" rx="1"/><path d="M14 5.5 17 3l1.4 1.4L15.6 7z"/><circle cx="19.5" cy="3.5" r="1.8" opacity=".6"/>',
    module: './games/bombes.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Bombe', aria: 'Poser une bombe' }] },
    livesLabel: 'Vies',
    touchKeys: 'La croix déplace, « Bombe » pose. La sortie n’ouvre qu’une fois tous les ennemis soufflés.',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> déplacent · <kbd>Espace</kbd> pose une bombe. La sortie, cachée sous une brique, n’ouvre qu’une fois tous les ennemis soufflés.',
    higherIsBetter: true,
  },
  {
    id: 'pyramide',
    name: 'Pyramide',
    ink: 'var(--jade)',
    category: 'Arcade',
    difficulty: 3,
    new: true,
    description: 'Vingt-huit cubes à changer de couleur, en sautant uniquement en diagonale. Les boules descendent, le vide attend, et un disque te sauve une fois par tableau.',
    glyph: '<path d="M12 2 16 5 12 8 8 5z"/><path d="M8 7 12 10 8 13 4 10z" opacity=".8"/><path d="M16 7 20 10 16 13 12 10z" opacity=".8"/><path d="M12 12 16 15 12 18 8 15z" opacity=".6"/><path d="M4 17 8 20 4 23 0 20z" opacity=".4"/>',
    module: './games/pyramide.js',
    touch: { pad: 'dpad', actions: [] },
    livesLabel: 'Vies',
    touchKeys: 'Touche le quart de l’écran correspondant à la diagonale voulue, ou utilise la croix. Haut = en haut à gauche, droite = en haut à droite.',
    keys: 'Les quatre flèches sautent en diagonale : <kbd>↑</kbd> en haut à gauche · <kbd>→</kbd> en haut à droite · <kbd>↓</kbd> en bas à droite · <kbd>←</kbd> en bas à gauche.',
    higherIsBetter: true,
  },
  {
    id: 'tuyaux',
    name: 'Tuyaux',
    ink: 'var(--azure)',
    category: 'Puzzle',
    difficulty: 3,
    new: true,
    description: 'Pose les pièces qui arrivent avant que l’eau ne parte. Une fois lâchée, elle ne s’arrête plus : il faut un tuyau assez long, et aucune fuite.',
    glyph: '<path d="M2 8h8a4 4 0 0 1 4 4v10" stroke="currentColor" stroke-width="3.4" fill="none" stroke-linecap="round"/><path d="M22 4v6a4 4 0 0 1-4 4h-4" stroke="currentColor" stroke-width="3.4" fill="none" stroke-linecap="round" opacity=".55"/>',
    module: './games/tuyaux.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Poser', aria: 'Poser la pièce' }] },
    livesLabel: 'Essais',
    touchKeys: 'Touche une case pour y poser la pièce du haut de la file. La croix et « Poser » marchent aussi.',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> déplacent le curseur · <kbd>Espace</kbd> pose la pièce. Le clic pose directement. Un tuyau pas encore mouillé peut être recouvert.',
    higherIsBetter: true,
  },
  {
    id: 'eboulis',
    name: 'Éboulis',
    ink: 'var(--steel)',
    category: 'Puzzle',
    difficulty: 4,
    new: true,
    description: 'Creuse la grotte, ramasse ton quota de diamants, sors avant la fin du temps. Les rochers tombent, roulent sur les dos ronds et ne pardonnent pas.',
    glyph: '<circle cx="7" cy="6" r="4"/><circle cx="17" cy="9" r="3.4" opacity=".7"/><path d="M12 14l4 4-4 4-4-4z"/><rect x="2" y="19" width="6" height="4" rx="1" opacity=".5"/>',
    module: './games/eboulis.js',
    touch: { pad: 'dpad', actions: [] },
    livesLabel: 'Vies',
    touchKeys: 'La croix creuse dans la direction choisie. On pousse un rocher à l’horizontale, s’il a de la place.',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> creusent. On pousse un rocher à l’horizontale s’il a de la place derrière lui. La sortie n’ouvre qu’au quota de diamants.',
    higherIsBetter: true,
  },
];

export function getGame(id) {
  return GAMES.find((g) => g.id === id);
}

export function stars(n) {
  return '★'.repeat(n) + '☆'.repeat(5 - n);
}

export function glyphSVG(game, size = 24) {
  return `<svg class="glyph" width="${size}" height="${size}" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">${game.glyph}</svg>`;
}
