// Central game registry. Add a game: drop a module in js/games/, add an entry here.
// `ink`   — the cabinet's spot colour; identifies the game on card, marquee and scores.
// `glyph` — original flat-ink art (inner markup of a 24x24 viewBox, fill: currentColor).
// `touch` — { pad, actions } describing the on-screen controls for coarse pointers.
//           pad: 'dpad' | 'lr' | 'ud' | null. actions: [{ a, label, aria }]

export const GAMES = [
  {
    id: 'pong',
    name: 'Pong',
    ink: 'var(--flame)',
    category: 'Classique',
    difficulty: 2,
    description: "Deux raquettes, une balle, aucune excuse. L'angle de renvoi dépend de l'endroit touché.",
    glyph: '<rect x="2" y="7" width="2.4" height="10"/><rect x="19.6" y="9" width="2.4" height="10"/><circle cx="12" cy="12" r="2.4"/>',
    module: './games/pong.js',
    touch: { pad: 'ud', actions: [] },
    touchKeys: "Les flèches sous l’écran montent et descendent ta raquette.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> déplacent ta raquette.',
    higherIsBetter: true,
  },
  {
    id: 'pacman',
    name: 'Croque-Labyrinthe',
    ink: 'var(--amber)',
    category: 'Arcade',
    difficulty: 3,
    description: 'Labyrinthe différent à chaque niveau. Les gélules inversent le rapport de force.',
    glyph: '<path d="M21.6 6.2 12.4 12l9.2 5.8A10 10 0 1 1 21.6 6.2Z"/>',
    module: './games/pacman.js',
    touch: { pad: 'dpad', actions: [] },
    touchKeys: "La croix directionnelle sous l’écran te déplace. Les tunnels latéraux traversent l’écran.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> pour te déplacer. Les tunnels latéraux traversent l\'écran.',
    higherIsBetter: true,
  },
  {
    id: 'tetris',
    name: 'Tetris',
    ink: 'var(--jade)',
    category: 'Puzzle',
    difficulty: 3,
    description: 'Sac de 7, pièce en garde, délai de verrouillage. Les règles modernes, au complet.',
    glyph: '<rect x="8" y="6" width="5" height="5"/><rect x="2" y="12" width="5" height="5"/><rect x="8" y="12" width="5" height="5"/><rect x="14" y="12" width="5" height="5"/>',
    module: './games/tetris.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Pose', aria: 'Poser la pièce' }, { a: 'hold', label: 'Garde', aria: 'Mettre la pièce en garde' }] },
    touchKeys: "Croix : déplacer, ↑ tourne, ↓ accélère · Pose la pièce d’un coup · Garde la met de côté.",
    keys: '<kbd>←</kbd> <kbd>→</kbd> déplacent · <kbd>↑</kbd> tourne · <kbd>↓</kbd> accélère · <kbd>Espace</kbd> pose d\'un coup · <kbd>C</kbd> met en garde.',
    higherIsBetter: true,
  },
  {
    id: 'invaders',
    name: 'Vague Zéro',
    ink: 'var(--grape)',
    category: 'Action',
    difficulty: 3,
    description: 'Abris destructibles, bonus qui tombent, et un boss toutes les quatre vagues.',
    glyph: '<path d="M6 6h2v2H6zM16 6h2v2h-2zM8 8h8v2H8zM6 10h12v2H6zM4 12h16v2H4zM4 14h4v2H4zM16 14h4v2h-4zM8 16h2v2H8zM14 16h2v2h-2z"/>',
    module: './games/invaders.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Tir', aria: 'Tirer' }] },
    touchKeys: "← → déplacent le canon, Tir tire.",
    keys: '<kbd>←</kbd> <kbd>→</kbd> déplacent le canon · <kbd>Espace</kbd> tire.',
    higherIsBetter: true,
  },
  {
    id: 'snake',
    name: 'Serpent',
    ink: 'var(--lime)',
    category: 'Arcade',
    difficulty: 2,
    description: 'Il grandit, tu rétrécis. Les virages sont mis en file : tes doubles appuis passent.',
    glyph: '<path d="M4 4h10v4H8v4h10v8H6v-4h8v-2H4z"/>',
    module: './games/snake.js',
    touch: { pad: 'dpad', actions: [] },
    touchKeys: "La croix directionnelle fait tourner le serpent. Le carré doré rapporte gros, mais il expire.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> pour tourner. Le carré doré rapporte gros, mais il expire.',
    higherIsBetter: true,
  },
  {
    id: 'breakout',
    name: 'Casse-Brique',
    ink: 'var(--azure)',
    category: 'Arcade',
    difficulty: 2,
    description: "L'angle dépend de l'endroit où la balle touche la raquette. Bonus : large, multi-balle, vie.",
    glyph: '<rect x="2" y="4" width="6" height="3"/><rect x="9" y="4" width="6" height="3"/><rect x="16" y="4" width="6" height="3"/><rect x="5" y="9" width="6" height="3"/><rect x="12" y="9" width="6" height="3"/><rect x="7" y="19" width="10" height="3"/><circle cx="12" cy="15" r="2"/>',
    module: './games/breakout.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Lancer', aria: 'Lancer la balle' }] },
    touchKeys: "← → déplacent la raquette, Lancer envoie la balle.",
    keys: '<kbd>←</kbd> <kbd>→</kbd> déplacent la raquette · <kbd>Espace</kbd> lance la balle.',
    higherIsBetter: true,
  },
  {
    id: '2048',
    name: '2048',
    ink: 'var(--rose)',
    category: 'Puzzle',
    difficulty: 2,
    description: 'Pousse la grille, fusionne les paires. Atteindre 2048 est une victoire, pas une fin.',
    glyph: '<rect x="2" y="2" width="9" height="9"/><rect x="13" y="2" width="9" height="9"/><rect x="2" y="13" width="9" height="9"/><rect x="13" y="13" width="9" height="9" opacity=".45"/>',
    module: './games/2048.js',
    touch: { pad: 'dpad', actions: [] },
    touchKeys: "La croix directionnelle pousse toute la grille.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> poussent toute la grille.',
    higherIsBetter: true,
  },
  {
    id: 'minesweeper',
    name: 'Démineur',
    ink: 'var(--steel)',
    category: 'Puzzle',
    difficulty: 4,
    description: 'Trente mines, aucune devinette au premier clic : la grille se pose autour de toi.',
    glyph: '<circle cx="12" cy="13" r="6"/><rect x="11" y="3" width="2" height="5"/><rect x="3" y="12" width="4" height="2"/><rect x="17" y="12" width="4" height="2"/>',
    module: './games/minesweeper.js',
    touch: { pad: null, actions: [{ a: 'action', label: 'Drapeau', aria: 'Basculer le mode drapeau' }] },
    livesLabel: 'Mines',   // this game reports mines left, not lives
    touchKeys: "Touche une case pour la révéler. Drapeau bascule le mode : la case suivante reçoit un drapeau.",
    keys: 'Clic pour révéler · clic droit pour poser un drapeau · <kbd>F</kbd> bascule le mode drapeau.',
    higherIsBetter: true,
  },
  {
    id: 'simon',
    name: 'Simon',
    ink: 'var(--rose)',
    category: 'Réflexe',
    difficulty: 2,
    description: "Regarde la séquence, refais-la. Chaque quartier a sa note : ça s'écoute autant que ça se voit.",
    glyph: '<path d="M12 2a10 10 0 0 1 10 10h-7a3 3 0 0 0-3-3z"/><path d="M22 12a10 10 0 0 1-10 10v-7a3 3 0 0 0 3-3z" opacity=".75"/><path d="M12 22A10 10 0 0 1 2 12h7a3 3 0 0 0 3 3z" opacity=".55"/><path d="M2 12A10 10 0 0 1 12 2v7a3 3 0 0 0-3 3z" opacity=".35"/>',
    module: './games/simon.js',
    touch: { pad: 'dpad', actions: [] },
    livesLabel: 'Erreurs',
    touchKeys: "Touche directement les quartiers de couleur à l’écran.",
    keys: 'Clique un quartier, ou <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> <kbd>←</kbd> pour les quatre couleurs.',
    higherIsBetter: true,
  },
  {
    id: 'flappy',
    name: "Bat d'Aile",
    ink: 'var(--jade)',
    category: 'Réflexe',
    difficulty: 4,
    description: 'Une seule touche. Les ouvertures se resserrent à mesure que tu passes.',
    glyph: '<path d="M4 6h5v3H4zM14 2h6v20h-6zM4 15h5v3H4z"/><circle cx="11" cy="12" r="2.6"/>',
    module: './games/flappy.js',
    touch: { pad: null, actions: [{ a: 'action', label: 'Voler', aria: 'Battre des ailes' }] },
    touchKeys: "Voler — ou une touche n’importe où sur l’écran — bat des ailes.",
    keys: '<kbd>Espace</kbd> (ou un clic) pour battre des ailes.',
    higherIsBetter: true,
  },
  {
    id: 'connect4',
    name: 'Puissance 4',
    ink: 'var(--azure)',
    category: 'Réflexion',
    difficulty: 3,
    description: "Contre une IA qui anticipe. Enchaîne les manches : ton score, c'est ta série.",
    glyph: '<rect x="2" y="4" width="20" height="18" rx="2" opacity=".35"/><circle cx="7" cy="17" r="2.4"/><circle cx="12" cy="17" r="2.4"/><circle cx="12" cy="12" r="2.4"/><circle cx="17" cy="17" r="2.4"/>',
    module: './games/connect4.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Poser', aria: 'Poser un jeton' }] },
    livesLabel: 'Série',
    touchKeys: "Touche une colonne à l’écran pour y poser ton jeton.",
    keys: 'Clique une colonne, ou <kbd>←</kbd> <kbd>→</kbd> pour viser et <kbd>Espace</kbd> pour poser.',
    higherIsBetter: true,
  },
  {
    id: 'memory',
    name: 'Paires',
    ink: 'var(--lime)',
    category: 'Réflexion',
    difficulty: 2,
    description: 'Retourne deux cartes, garde la paire. Moins de coups et moins de temps : plus de points.',
    glyph: '<rect x="2" y="3" width="8" height="8" rx="1"/><rect x="14" y="3" width="8" height="8" rx="1" opacity=".4"/><rect x="2" y="13" width="8" height="8" rx="1" opacity=".4"/><rect x="14" y="13" width="8" height="8" rx="1"/>',
    module: './games/memory.js',
    touch: { pad: null, actions: [] },
    livesLabel: 'Coups',
    touchKeys: "Touche une carte à l’écran pour la retourner.",
    keys: 'Clique (ou touche) une carte pour la retourner.',
    higherIsBetter: true,
  },
];

export function getGame(id) {
  return GAMES.find((g) => g.id === id);
}

export function stars(n) {
  return '★'.repeat(n) + '☆'.repeat(5 - n);
}

export function glyphSVG(game, size = 24) {
  return `<svg class="glyph" width="${size}" height="${size}" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">${game.glyph}</svg>`;
}
