// Central game registry. Add a game: drop a module in js/games/, add an entry here.
// `ink`   — the cabinet's spot colour; identifies the game on card, marquee and scores.
// `glyph` — original flat-ink art (inner markup of a 24x24 viewBox, fill: currentColor).
// `touch` — { pad, actions } describing the on-screen controls for coarse pointers.
//           pad: 'dpad' | 'lr' | 'ud' | null. actions: [{ a, label, aria }]
// `swipe` — true: a swipe on the screen is a d-pad press. An object remaps a
//           direction or adds a tap: { down: 'action', tap: 'up' }.
// `music` — a song id from audio.js SONGS, looped while playing.

export const GAMES = [
  {
    id: 'pong',
    name: 'Pong',
    ink: 'var(--flame)',
    category: 'Classique',
    difficulty: 2,
    description: "Deux raquettes, une balle, trois bips. L'angle de renvoi dépend de l'endroit touché.",
    glyph: '<rect x="2" y="7" width="2.4" height="10"/><rect x="19.6" y="9" width="2.4" height="10"/><circle cx="12" cy="12" r="2.4"/>',
    module: './games/pong.js',
    touch: { pad: 'ud', actions: [] },
    touchKeys: "Fais glisser ton doigt sur l’écran : la raquette le suit. Les flèches marchent aussi.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> ou la souris sur l’écran déplacent ta raquette.',
    higherIsBetter: true,
  },
  {
    id: 'pacman',
    name: 'Croque-Labyrinthe',
    ink: 'var(--amber)',
    category: 'Arcade',
    difficulty: 3,
    description: 'Quatre fantômes, quatre caractères. Les gélules inversent le rapport de force, les fruits paient.',
    glyph: '<path d="M21.6 6.2 12.4 12l9.2 5.8A10 10 0 1 1 21.6 6.2Z"/>',
    module: './games/pacman.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: "Glisse sur l’écran ou utilise la croix. Les tunnels latéraux traversent l’écran.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> pour te déplacer. Les tunnels latéraux traversent l\'écran.',
    higherIsBetter: true,
  },
  {
    id: 'tetris',
    name: 'Tetris',
    ink: 'var(--jade)',
    category: 'Puzzle',
    difficulty: 3,
    description: 'Sac de 7, pièce en garde, délai de verrouillage. Les règles modernes, au complet.',
    glyph: '<rect x="8" y="6" width="5" height="5"/><rect x="2" y="12" width="5" height="5"/><rect x="8" y="12" width="5" height="5"/><rect x="14" y="12" width="5" height="5"/>',
    module: './games/tetris.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Pose', aria: 'Poser la pièce' }, { a: 'hold', label: 'Garde', aria: 'Mettre la pièce en garde' }] },
    swipe: { down: 'action', tap: 'up' },
    music: 'korobeiniki',
    touchKeys: "Sur l’écran : glisse ← → pour déplacer, touche pour tourner, glisse ↓ pour poser. La croix et Garde restent dessous.",
    keys: '<kbd>←</kbd> <kbd>→</kbd> déplacent · <kbd>↑</kbd> tourne · <kbd>↓</kbd> accélère · <kbd>Espace</kbd> pose d\'un coup · <kbd>C</kbd> met en garde.',
    higherIsBetter: true,
  },
  {
    id: 'invaders',
    name: 'Vague Zéro',
    ink: 'var(--grape)',
    category: 'Action',
    difficulty: 3,
    description: 'Onze colonnes qui marchent au rythme du cœur. Un seul tir à la fois, et une soucoupe à abattre.',
    glyph: '<path d="M6 6h2v2H6zM16 6h2v2h-2zM8 8h8v2H8zM6 10h12v2H6zM4 12h16v2H4zM4 14h4v2H4zM16 14h4v2h-4zM8 16h2v2H8zM14 16h2v2h-2z"/>',
    module: './games/invaders.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Tir', aria: 'Tirer' }] },
    touchKeys: "← → déplacent le canon, Tir tire.",
    keys: '<kbd>←</kbd> <kbd>→</kbd> déplacent le canon · <kbd>Espace</kbd> tire.',
    higherIsBetter: true,
  },
  {
    id: 'snake',
    name: 'Serpent',
    ink: 'var(--lime)',
    category: 'Arcade',
    difficulty: 2,
    description: 'Il grandit, tu rétrécis. Les virages sont mis en file : tes doubles appuis passent.',
    glyph: '<path d="M4 4h10v4H8v4h10v8H6v-4h8v-2H4z"/>',
    module: './games/snake.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: "Glisse sur l’écran ou utilise la croix pour tourner. Le carré doré rapporte gros, mais il expire.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> pour tourner. Le carré doré rapporte gros, mais il expire.',
    higherIsBetter: true,
  },
  {
    id: 'breakout',
    name: 'Casse-Brique',
    ink: 'var(--azure)',
    category: 'Arcade',
    difficulty: 2,
    description: "Huit rangées, quatre couleurs. La balle accélère, la raquette rétrécit au plafond — les règles de 1976.",
    glyph: '<rect x="2" y="4" width="6" height="3"/><rect x="9" y="4" width="6" height="3"/><rect x="16" y="4" width="6" height="3"/><rect x="5" y="9" width="6" height="3"/><rect x="12" y="9" width="6" height="3"/><rect x="7" y="19" width="10" height="3"/><circle cx="12" cy="15" r="2"/>',
    module: './games/breakout.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Lancer', aria: 'Lancer la balle' }] },
    touchKeys: "Fais glisser ton doigt sur l’écran : la raquette le suit. Touche pour lancer.",
    keys: 'La souris ou <kbd>←</kbd> <kbd>→</kbd> déplacent la raquette · <kbd>Espace</kbd> lance la balle.',
    higherIsBetter: true,
  },
  {
    id: '2048',
    name: '2048',
    ink: 'var(--rose)',
    category: 'Puzzle',
    difficulty: 2,
    description: 'Pousse la grille, fusionne les paires. Atteindre 2048 est une victoire, pas une fin.',
    glyph: '<rect x="2" y="2" width="9" height="9"/><rect x="13" y="2" width="9" height="9"/><rect x="2" y="13" width="9" height="9"/><rect x="13" y="13" width="9" height="9" opacity=".45"/>',
    module: './games/2048.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: "Glisse sur la grille (ou utilise la croix) pour tout pousser.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> poussent toute la grille.',
    higherIsBetter: true,
  },
  {
    id: 'minesweeper',
    name: 'Démineur',
    ink: 'var(--steel)',
    category: 'Puzzle',
    difficulty: 4,
    description: 'Trente mines, aucune devinette au premier clic : la grille se pose autour de toi.',
    glyph: '<circle cx="12" cy="13" r="6"/><rect x="11" y="3" width="2" height="5"/><rect x="3" y="12" width="4" height="2"/><rect x="17" y="12" width="4" height="2"/>',
    module: './games/minesweeper.js',
    touch: { pad: null, actions: [{ a: 'action', label: 'Drapeau', aria: 'Basculer le mode drapeau' }] },
    livesLabel: 'Mines',   // this game reports mines left, not lives
    touchKeys: "Touche une case pour la révéler. Drapeau bascule le mode : la case suivante reçoit un drapeau.",
    keys: 'Clic pour révéler · clic droit pour poser un drapeau · <kbd>F</kbd> bascule le mode drapeau.',
    higherIsBetter: true,
  },
  {
    id: 'simon',
    name: 'Simon',
    ink: 'var(--rose)',
    category: 'Réflexe',
    difficulty: 2,
    description: "Regarde la séquence, refais-la. Chaque quartier a sa note : ça s'écoute autant que ça se voit.",
    glyph: '<path d="M12 2a10 10 0 0 1 10 10h-7a3 3 0 0 0-3-3z"/><path d="M22 12a10 10 0 0 1-10 10v-7a3 3 0 0 0 3-3z" opacity=".75"/><path d="M12 22A10 10 0 0 1 2 12h7a3 3 0 0 0 3 3z" opacity=".55"/><path d="M2 12A10 10 0 0 1 12 2v7a3 3 0 0 0-3 3z" opacity=".35"/>',
    module: './games/simon.js',
    touch: { pad: 'dpad', actions: [] },
    livesLabel: 'Erreurs',
    touchKeys: "Touche directement les quartiers de couleur à l’écran.",
    keys: 'Clique un quartier, ou <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> <kbd>←</kbd> pour les quatre couleurs.',
    higherIsBetter: true,
  },
  {
    id: 'flappy',
    name: "Bat d'Aile",
    ink: 'var(--jade)',
    category: 'Réflexe',
    difficulty: 4,
    description: 'Une seule touche. Les ouvertures se resserrent à mesure que tu passes.',
    glyph: '<path d="M4 6h5v3H4zM14 2h6v20h-6zM4 15h5v3H4z"/><circle cx="11" cy="12" r="2.6"/>',
    module: './games/flappy.js',
    touch: { pad: null, actions: [{ a: 'action', label: 'Voler', aria: 'Battre des ailes' }] },
    touchKeys: "Voler — ou une touche n’importe où sur l’écran — bat des ailes.",
    keys: '<kbd>Espace</kbd> (ou un clic) pour battre des ailes.',
    higherIsBetter: true,
  },
  {
    id: 'connect4',
    name: 'Puissance 4',
    ink: 'var(--azure)',
    category: 'Réflexion',
    difficulty: 3,
    description: "Contre une IA qui anticipe. Enchaîne les manches : ton score, c'est ta série.",
    glyph: '<rect x="2" y="4" width="20" height="18" rx="2" opacity=".35"/><circle cx="7" cy="17" r="2.4"/><circle cx="12" cy="17" r="2.4"/><circle cx="12" cy="12" r="2.4"/><circle cx="17" cy="17" r="2.4"/>',
    module: './games/connect4.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Poser', aria: 'Poser un jeton' }] },
    livesLabel: 'Série',
    touchKeys: "Touche une colonne à l’écran pour y poser ton jeton.",
    keys: 'Clique une colonne, ou <kbd>←</kbd> <kbd>→</kbd> pour viser et <kbd>Espace</kbd> pour poser.',
    higherIsBetter: true,
  },
  {
    id: 'memory',
    name: 'Paires',
    ink: 'var(--lime)',
    category: 'Réflexion',
    difficulty: 2,
    description: 'Retourne deux cartes, garde la paire. Moins de coups et moins de temps : plus de points.',
    glyph: '<rect x="2" y="3" width="8" height="8" rx="1"/><rect x="14" y="3" width="8" height="8" rx="1" opacity=".4"/><rect x="2" y="13" width="8" height="8" rx="1" opacity=".4"/><rect x="14" y="13" width="8" height="8" rx="1"/>',
    module: './games/memory.js',
    touch: { pad: null, actions: [] },
    livesLabel: 'Coups',
    touchKeys: "Touche une carte à l’écran pour la retourner.",
    keys: 'Clique (ou touche) une carte pour la retourner.',
    higherIsBetter: true,
  },
  {
    id: 'asteroids',
    name: 'Astéroïdes',
    ink: 'var(--steel)',
    category: 'Action',
    difficulty: 4,
    description: 'Un vaisseau, de l’inertie et des rochers qui se brisent en trois tailles. En traits lumineux, comme en 1979.',
    glyph: '<path d="M3 13.5 6.5 10h4l2.5 2.5-1.2 3 2 2.3-2.3 3.2H7l-4-2.6z" opacity=".55"/><path d="M17.5 2 22 12l-4.5-2.4L13 12z"/>',
    module: './games/asteroids.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Tir', aria: 'Tirer' }] },
    touchKeys: "← → tournent, ↑ pousse, ↓ hyperespace (risqué) · Tir tire.",
    keys: '<kbd>←</kbd> <kbd>→</kbd> tournent · <kbd>↑</kbd> pousse · <kbd>Espace</kbd> tire · <kbd>↓</kbd> hyperespace.',
    higherIsBetter: true,
  },
  {
    id: 'frogger',
    name: 'Traversée',
    ink: 'var(--lime)',
    category: 'Arcade',
    difficulty: 3,
    description: 'Cinq voies de circulation, une rivière, cinq abris à rejoindre. Les tortues plongent sans prévenir.',
    glyph: '<path d="M7 3h3v3H7zM14 3h3v3h-3zM6 6h12v9H6zM3 8h3v4H3zM18 8h3v4h-3zM3 15h5v5H3zM16 15h5v5h-5zM9 15h6v3H9z"/>',
    module: './games/frogger.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: "Glisse sur l’écran ou touche la croix : un saut par geste.",
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> : un saut par appui.',
    higherIsBetter: true,
  },
  {
    id: 'missile',
    name: 'Riposte',
    ink: 'var(--flame)',
    category: 'Action',
    difficulty: 3,
    description: 'Six villes, trois silos, des missiles qui tombent. Vise devant eux : les explosions s’enchaînent.',
    glyph: '<circle cx="15" cy="9" r="5"/><path d="M2 20h20v2H2zM4 17h3v3H4zM10.5 16h3v4h-3zM17 17h3v3h-3zM2.6 2 4 1.2 10 11.5l-1.4.8z"/>',
    module: './games/missile.js',
    touch: { pad: null, actions: [] },
    livesLabel: 'Villes',
    touchKeys: "Touche l’écran là où le missile va passer : le silo le plus proche tire.",
    keys: 'Clique où le missile va passer, ou vise avec <kbd>←</kbd> <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> et tire avec <kbd>Espace</kbd>.',
    higherIsBetter: true,
  },
  {
    id: 'galaxian',
    name: 'Galaxie',
    ink: 'var(--grape)',
    category: 'Action',
    difficulty: 3,
    description: 'Une flotte qui ondule, des pillards qui plongent en piqué, des vaisseaux amiraux escortés. Un tir à la fois.',
    glyph: '<path d="M7 3h2v2H7zM15 3h2v2h-2zM6 5h12v3H6zM4 8h16v3H4zM4 11h3v3H4zM17 11h3v3h-3z"/><path d="M11 15h2v3h2v3H9v-3h2z" opacity=".55"/>',
    module: './games/galaxian.js',
    touch: { pad: 'lr', actions: [{ a: 'action', label: 'Tir', aria: 'Tirer' }] },
    touchKeys: '← → déplacent le vaisseau, Tir tire. Un amiral abattu en piqué après ses escortes vaut 800.',
    keys: '<kbd>←</kbd> <kbd>→</kbd> déplacent le vaisseau · <kbd>Espace</kbd> tire.',
    higherIsBetter: true,
  },
  {
    id: 'centipede',
    name: 'Mille-pattes',
    ink: 'var(--lime)',
    category: 'Action',
    difficulty: 3,
    description: 'Il descend entre les champignons et se coupe en deux à chaque tir. L’araignée rôde dans ton coin.',
    glyph: '<circle cx="5" cy="12" r="3"/><circle cx="11" cy="12" r="3" opacity=".75"/><circle cx="17" cy="12" r="3" opacity=".55"/><path d="M3 4h5v3H3zM16 3h5v3h-5zM10 18h4v4h-4z" opacity=".4"/>',
    module: './games/centipede.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Tir', aria: 'Tirer' }] },
    touchKeys: 'La croix déplace ton canon dans la zone du bas, Tir tire (garde appuyé pour tirer en continu).',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> déplacent le canon · <kbd>Espace</kbd> tire (maintenu : en continu).',
    higherIsBetter: true,
  },
  {
    id: 'lander',
    name: 'Alunissage',
    ink: 'var(--steel)',
    category: 'Réflexion',
    difficulty: 4,
    description: 'Dose la poussée, redresse le module, pose-toi en douceur. Plus la piste est étroite, plus elle paie.',
    glyph: '<path d="M8 3h8l2 4v3H6V7zM5 10h14v3H5zM6 13l-3 6h2l3-6zM18 13l3 6h-2l-3-6z"/><path d="M1 21h22v1.5H1z" opacity=".5"/>',
    module: './games/lander.js',
    touch: { pad: 'dpad', actions: [{ a: 'action', label: 'Poussée', aria: 'Allumer le moteur' }] },
    livesLabel: 'Carburant',
    touchKeys: '← → inclinent le module, ↑ ou Poussée allume le moteur. Vitesses en rouge : trop vite pour se poser.',
    keys: '<kbd>←</kbd> <kbd>→</kbd> inclinent · <kbd>↑</kbd> ou <kbd>Espace</kbd> pour la poussée.',
    higherIsBetter: true,
  },
  {
    id: 'lightcycles',
    name: 'Motos lumière',
    ink: 'var(--azure)',
    category: 'Réflexe',
    difficulty: 3,
    description: 'Chaque moto laisse un mur de lumière. Coince les autres, ne touche rien. Un rival de plus à chaque manche.',
    glyph: '<path d="M2 4h10v3H5v10H2zM12 4h3v12h7v3H12z" opacity=".55"/><path d="M4 16h3v3H4zM19 7h3v3h-3z"/>',
    module: './games/lightcycles.js',
    touch: { pad: 'dpad', actions: [] },
    swipe: true,
    touchKeys: 'Glisse sur l’écran ou touche la croix pour tourner. Deux appuis rapides comptent tous les deux.',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> pour tourner.',
    higherIsBetter: true,
  },
  {
    id: 'doom',
    name: 'Freedoom',
    ink: 'var(--flame)',
    category: 'Action',
    difficulty: 4,
    description: 'Le moteur de Doom (1993) avec Freedoom, un Doom complet et libre en 4 épisodes. Tu as le jeu original ? Charge ton DOOM.WAD.',
    glyph: '<path d="M4 3h16l-1.5 4H17v3l2 2-2 1v6l-5 3-5-3v-6l-2-1 2-2V7H5.5z" opacity=".35"/><path d="M8.5 11h2.5v2.5H8.5zM13 11h2.5v2.5H13zM10 16.5h4V18h-4z"/>',
    module: './games/doom.js',
    custom: true,            // its own menus, skills and saves: no score, level or difficulty strip
    filePicker: { accept: '.wad,.WAD', label: 'Charger mon DOOM.WAD' },
    touch: { pad: 'dpad', actions: [
      { a: 'action', label: 'Tir', aria: 'Tirer, ou valider dans les menus' },
      { a: 'hold', label: 'Ouvrir', aria: 'Ouvrir une porte, actionner un levier' },
      { a: 'weapon', label: 'Arme', aria: 'Arme suivante' },
      { a: 'menu', label: 'Menu', aria: 'Ouvrir le menu' },
    ] },
    touchKeys: 'Croix : avancer et tourner · Tir (valide aussi les menus) · Ouvrir les portes · Arme suivante · Menu. Tu cours en permanence. Sauvegardes gardées dans ce navigateur.',
    keys: '<kbd>↑</kbd> <kbd>↓</kbd> <kbd>←</kbd> <kbd>→</kbd> · <kbd>Ctrl</kbd> tire · <kbd>Espace</kbd> ouvre · <kbd>Maj</kbd> court · <kbd>Alt</kbd>+flèches ou <kbd>,</kbd> <kbd>.</kbd> en pas de côté · <kbd>1</kbd>–<kbd>7</kbd> armes · <kbd>Tab</kbd> carte · <kbd>Échap</kbd> menu (sauvegarder, charger, difficulté).',
    higherIsBetter: true,
  },
];

export function getGame(id) {
  return GAMES.find((g) => g.id === id);
}

export function stars(n) {
  return '★'.repeat(n) + '☆'.repeat(5 - n);
}

export function glyphSVG(game, size = 24) {
  return `<svg class="glyph" width="${size}" height="${size}" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">${game.glyph}</svg>`;
}
